<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2QQTh6G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2QQTh6G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2QQTh6G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2QQTh6G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2QQTh6G\App_KernelDevDebugContainer([
    'container.build_hash' => '2QQTh6G',
    'container.build_id' => 'f62b9175',
    'container.build_time' => 1721637508,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2QQTh6G');
